### ISSUE TITLE
Problems with Typo3 version 7.6.11

### ISSUE THREAD

**Issue by Subco** [svewap/realurl_404_multilingual#13]
Hi,

first of all thank you for the great extension. Works very easy and perfect. But since the new typo3 version 7.6.11 there's a problem with the recommended configuration option:
`$GLOBALS['TYPO3_CONF_VARS']['FE']['cHashIncludePageId'] = true;`

As typo3.org recommends the new security update and the configuration setting above should prevent 'cache flooding'. The update itself is no problem but as soon as I set the config option to true the realurl_404_multilingual extension throws a lots of errors and doesn't work anymore.

The protocoll says:
`Core: Error handler (FE): PHP Warning: file_get_contents(.../?tx_realurl404multilingual=1): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found in /.../typo3conf/ext/realurl_404_multilingual/Classes/Hooks/FrontendHook.php line 308`

I hope you know a fix for it because I really want to keep up with your great extension.

**Comment by svewap** [comment]
Thanks for your bug report. I will try to fix it!

**Comment by svewap** [comment]
Hi! I activated the cHashIncludePageId setting, but my 404 pages were shown without problems. Maybe the path to the 404 page is wrong? I made an improvement: If the 404 page was not found, it generates a small 404 warning page. Maybe you can checkout the newest version and test it. But I think your 404 page cannot be accessed. I updated the documentation too. The settings have changed.

**Comment by Subco** [comment]
Hi. I updated the extension. It seems that the errors disappeared but as soon as I set the option:
`$GLOBALS['TYPO3_CONF_VARS']['FE']['cHashIncludePageId'] = true;`
the 404 page is not accessible. Without the option everything works well.
