### ISSUE TITLE
Use TYPO3\CMS\Core\Http\RequestFactory instead of manual curl connection

### ISSUE THREAD

**Issue by alexanderschnitzler** [svewap/realurl_404_multilingual#19]
Hi Sven,

with https://github.com/TYPO3/TYPO3.CMS/commit/23fa188f7f2193fc07b443d04c0f7d493ecb7043 (TYPO3 8.1), the configuration for curl and http adapter has been removed from the core. (Example: `$GLOBALS['TYPO3_CONF_VARS']['SYS']['curlUse']` has been removed, see https://github.com/TYPO3/TYPO3.CMS/commit/23fa188f7f2193fc07b443d04c0f7d493ecb7043#diff-6b7ad7e5286e31e9dc5b7c598e07d16bR15 for all removed configuration keys)

Of course it's still possible to set the values manually in your `AdditionalConfiguration.php`, but it's not possible to set them via install tool. While the current approach still works with manual workarounds, it would make sense to switch to guzzle in form of the `TYPO3\CMS\Core\Http\RequestFactory`. It should be quite easy to use that as a drop in replacement for the manual curl connection in your extension.

Did you think about implementing that yourself and/or would a pull request be helpful?

**Comment by svewap** [comment]
Hi Alexander,
of course, I would also like to receive a pull request ;-)

**Comment by svewap** [comment]
I would prefer a seperate version by setting the dependencies to 8.7 . Old TYPO3 versions must not supported anymore.
