### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by maechler** [svewap/realurl_404_multilingual#21]
I just wanted to create an issue for the error that occurs when `$this->config['redirects']` is not an array. Then I saw you already fixed this issue, but it is not released yet. 
Could you please create a new release?

**Comment by svewap** [comment]
Soon. > 200 Mails to work through ;-)

**Comment by maechler** [comment]
No worries..thanks for publishing and maintaining this very useful extension!

**Comment by svewap** [comment]
new version released
