### ISSUE TITLE
Switch between redirect/curl

### ISSUE THREAD

**Issue by JLNNN** [svewap/realurl_404_multilingual#5]
Hi (again),

can you please make it selectable using redirect/curl? On some projects it's better staying on the URL you opened instead of being redirected to another page.

Thanks in advance,
  Julian

**Comment by svewap** [comment]
I'll look later when I have some time again.

**Comment by bernhardberger** [comment]
I agree with JLNNN, I recently updated realurl_404_multilingual in some projects and it caused unexpected behaviour and some other major issues. It also cost me a lot of time to even find what went wrong..

Unfortunately I had to downgrade to the release before.. I don't think it's a good idea in general to alter default behaviour so drastically and I would even argue that redirecting to a specific 404 page is kind of bad practice.

Please change it back the way it was and leave redirecting an option.. It was perfect the way it was. Major regression imho.

**Comment by anjeylink** [comment]
I need this switcher too, so i made a pull request with this feature. can you please check. Also i added there a fix to get a correct 404 page if there are FE login protected pages.
